### ISSUE TITLE
Could not find matching constructor for: DefaultExecAction

### ISSUE THREAD

**Issue by elion** [dkorotych/gradle-maven-exec-plugin#12]
Gradle fails with the following error:

An exception occurred applying plugin request [id: 'com.github.dkorotych.gradle-maven-exec', version: '1.2.1']
> Failed to apply plugin [id 'com.github.dkorotych.gradle-maven-exec']
   > Could not find matching constructor for: org.gradle.process.internal.DefaultExecAction(org.gradle.api.internal.file.IdentityFileResolver)

Other parts of stacktrace:

`Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.github.dkorotych.gradle-maven-exec']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:150)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:125)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$3.run(DefaultPluginRequestApplicator.java:151)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:225)
...
`

Gradle version:

Gradle 4.5.1
------------------------------------------------------------

Build time:   2018-02-05 13:22:49 UTC
Revision:     37007e1c012001ff09973e0bd095139239ecd3b3

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 10 10.0 amd64

**Comment by dkorotych** [comment]
Fixed at 1.2.2.1
